---
classes:
  - roles::puppetmaster

puppetdb::ssl_listen_address: 0.0.0.0
puppetdb::master::config::puppetdb_server: puppet
puppetdb::master::config::restart_puppet: false
puppetdb::master::config::manage_storeconfigs: false
puppetdb::globals::version: 2.3.7-1.el6

puppet::server: true
puppet::puppetmaster: puppet
puppet::runmode: none
puppet::hiera_config: /etc/hiera/hiera.yaml
puppet::server_external_nodes: ''
puppet::server_foreman: false
puppet::server_reports: puppetdb
puppet::server_storeconfigs_backend: puppetdb
puppet::server_implementation: master
puppet::server_environments: []

apache::manage_user: false
